# Site settings
title: Faclair nan Gèidheal
description: Faclair de bhriathrachas LGDTC+ Gàidhlig
brand: An Gèidheal Ùr
brand-link: https://angeidhealur.scot/
brand-tagline: Geàrr-chunntas sgrìobhte de naidheachdan LGDTCEN+ ionadail, nàiseanta ‘s bho air feadh an t-saoghail.
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://faclair.lgbt" # the base hostname & protocol for your site
excerpt_separator: <!--more-->

#footer
author-name: Crìstean MacMhìcheil
author-website: "https://criomagan.scot"

#social
mastodon: 
instagram: 
threads: 
email: fios@angeidhealur.scot

# Build settings
markdown: kramdown
permalink: /:year-:month-:day-:title/
paginate: 12
paginate_path: /duilleag-:num/

# Ruby Gems
plugins:
  - jekyll-paginate
  - jekyll-feed

collections:
  faclair:
    output: true
    permalink: /:path/
  focloir:
    output: true
    permalink: /:path/
  fockleyr:
    output: true
    permalink: /:path/
  glossary:
    output: true
    permalink: /:path/